apiVersion: v1
kind: Pod
metadata:
  name: nccl-test-2
spec:
  restartPolicy: Never
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "user-workload"
  - key: "nvidia.com/gpu"
    operator: "Exists"
  containers:
  - name: nccl-test
    image: public.ecr.aws/hpc-cloud/nccl-tests:latest
    command: ["/opt/nccl-tests/build/all_reduce_perf"]
    args: ["-b", "256M", "-e", "256M", "-g", "8"]
    resources:
      limits:
        nvidia.com/gpu: 8