// Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package initializer

import (
	"context"
	"testing"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"

	celenv "github.com/nvidia/nvsentinel/health-monitors/kubernetes-object-monitor/pkg/cel"
	"github.com/nvidia/nvsentinel/health-monitors/kubernetes-object-monitor/pkg/config"
)

// realPolicies are the kubernetes-object-monitor policies generated by the
// internal deployment configuration, copied verbatim from the rendered
// values.yaml of every test case in the nvsentinel-oss repository. The public
// Helm chart carries only commented-out examples, so these are the only
// representative inputs available for checking that field pruning does not
// change how a policy evaluates.
//
// They matter because they exercise constructs the benchmark policies never
// did: comprehensions nested inside comprehensions over the same list, two-level
// field access on an iteration variable (cs.state.waiting.reason), map indexing
// by literal key, and lookup() against another kind.
var realPolicies = []struct {
	name            string
	kind            string
	predicate       string
	nodeAssociation string
}{
	{
		name: "PodStuckAfterDeletion",
		kind: "Pod",
		predicate: `has(resource.metadata.deletionTimestamp)
&& has(resource.metadata.deletionGracePeriodSeconds)
&& has(resource.metadata.namespace)
&& resource.metadata.namespace in ["osmo-test", "osmo-prod-test"]
&& timestamp(resource.metadata.deletionTimestamp) + duration(string(resource.metadata.deletionGracePeriodSeconds * 2 + 3600) + "s") < now
&& resource.status.phase == "Running"
&& has(resource.spec.nodeName) && resource.spec.nodeName != ""
&& (!has(resource.status.containerStatuses)
  || !resource.status.containerStatuses.exists(cs,
       has(cs.state) && has(cs.state.waiting)
       && cs.state.waiting.reason == "CrashLoopBackOff"))`,
		nodeAssociation: `resource.spec.nodeName`,
	},
	{
		name: "ReplaceNotReadyNode",
		kind: "Node",
		predicate: `resource.status.conditions.exists(c,
  c.type == "Ready"
  && c.status != "True"
  && timestamp(c.lastTransitionTime) + duration("3600s") < now)`,
		nodeAssociation: ``,
	},
	{
		name: "OsmoReportedBadNode",
		kind: "Node",
		predicate: `resource.status.conditions.exists(c,
  c.type.startsWith('us-east-1-aws.osmo.nvidia.com/')
  && !(c.type in [
    'us-east-1-aws.osmo.nvidia.com/GpuIncorrectMode',
    'us-east-1-aws.osmo.nvidia.com/GpuIncorrectProduct',
    'us-east-1-aws.osmo.nvidia.com/GpuLessThanTotal',
    'us-east-1-aws.osmo.nvidia.com/NicsLessThanTotal',
    'us-east-1-aws.osmo.nvidia.com/ServiceConnectionTestFailure'
  ])
  && c.status == "True")`,
		nodeAssociation: ``,
	},
	{
		name: "PodStuckAfterDeletion",
		kind: "Pod",
		predicate: `has(resource.metadata.deletionTimestamp)
&& has(resource.metadata.deletionGracePeriodSeconds)
&& has(resource.metadata.namespace)
&& resource.metadata.namespace in ["osmo", "osmo-prod"]
&& timestamp(resource.metadata.deletionTimestamp) + duration(string(resource.metadata.deletionGracePeriodSeconds * 2 + 1800) + "s") < now
&& resource.status.phase == "Running"
&& has(resource.spec.nodeName) && resource.spec.nodeName != ""
&& (!has(resource.status.containerStatuses)
  || !resource.status.containerStatuses.exists(cs,
       has(cs.state) && has(cs.state.waiting)
       && cs.state.waiting.reason == "CrashLoopBackOff"))`,
		nodeAssociation: `resource.spec.nodeName`,
	},
	{
		name: "OsmoReportedBadNode",
		kind: "Node",
		predicate: `resource.status.conditions.exists(c,
  c.type.startsWith('us-west-2-aws.osmo.nvidia.com/')
  && !(c.type in [
    'us-west-2-aws.osmo.nvidia.com/GpuIncorrectMode',
    'us-west-2-aws.osmo.nvidia.com/GpuIncorrectProduct',
    'us-west-2-aws.osmo.nvidia.com/GpuLessThanTotal',
    'us-west-2-aws.osmo.nvidia.com/NicsLessThanTotal',
    'us-west-2-aws.osmo.nvidia.com/ServiceConnectionTestFailure'
  ])
  && c.type != 'us-west-2-aws.osmo.nvidia.com/LFSMountFailure'
  && c.status == "True")`,
		nodeAssociation: ``,
	},
	{
		name: "OsmoLFSMountFailure",
		kind: "Node",
		predicate: `resource.status.conditions.exists(c,
  c.type == 'us-west-2-aws.osmo.nvidia.com/LFSMountFailure'
  && c.status == "True"
  && has(c.lastHeartbeatTime)
  && resource.status.conditions.exists(r,
       r.type == "Ready" && r.status == "True"
       && timestamp(c.lastHeartbeatTime) > timestamp(r.lastTransitionTime) + duration("1800s")))`,
		nodeAssociation: ``,
	},
	{
		name:            "NodeNeedsRepair",
		kind:            "Node",
		predicate:       `resource.status.conditions.filter(c, c.type == "nke.nvidia.com/NeedsRepair" && c.status == "True").size() > 0`,
		nodeAssociation: ``,
	},
	{
		name:            "NodeNeedsRecycle",
		kind:            "Node",
		predicate:       `resource.status.conditions.filter(c, c.type == "nke.nvidia.com/NeedsRecycle" && c.status == "True").size() > 0`,
		nodeAssociation: ``,
	},
	{
		name: "OsmoReportedBadNode",
		kind: "Node",
		predicate: `resource.status.conditions.exists(c,
  c.type.startsWith('us-west-2-aws.osmo.nvidia.com/')
  && !(c.type in [
    'us-west-2-aws.osmo.nvidia.com/GpuIncorrectMode',
    'us-west-2-aws.osmo.nvidia.com/GpuIncorrectProduct',
    'us-west-2-aws.osmo.nvidia.com/GpuLessThanTotal',
    'us-west-2-aws.osmo.nvidia.com/NicsLessThanTotal',
    'us-west-2-aws.osmo.nvidia.com/ServiceConnectionTestFailure'
  ])
  && c.status == "True")`,
		nodeAssociation: ``,
	},
	{
		name: "GPUOperatorCudaValidatorRestarting",
		kind: "Pod",
		predicate: `resource.metadata.name.startsWith("nvidia-operator-validator-")
&& has(resource.spec.nodeName)
&& resource.spec.nodeName != ""
&& has(resource.status.initContainerStatuses)
&& resource.status.initContainerStatuses.exists(cs,
  cs.name == "cuda-validation"
  && cs.restartCount > 2)`,
		nodeAssociation: `lookup('v1', 'Node', '', resource.spec.nodeName).metadata.name`,
	},
	{
		name: "GPUOperatorCudaValidatorMissingClique",
		kind: "Pod",
		predicate: `resource.metadata.name.startsWith("nvidia-operator-validator-")
&& has(resource.spec.nodeName)
&& resource.spec.nodeName != ""
&& resource.status.phase == "Succeeded"
&& has(lookup('v1', 'Node', '', resource.spec.nodeName).metadata.labels)
&& "nvidia.com/gpu.product" in lookup('v1', 'Node', '', resource.spec.nodeName).metadata.labels
&& lookup('v1', 'Node', '', resource.spec.nodeName).metadata.labels["nvidia.com/gpu.product"].startsWith("NVIDIA-GB")
&& !("nvidia.com/gpu.clique" in lookup('v1', 'Node', '', resource.spec.nodeName).metadata.labels)`,
		nodeAssociation: `lookup('v1', 'Node', '', resource.spec.nodeName).metadata.name`,
	},
	{
		name: "SlinkySilentDrain",
		kind: "Pod",
		predicate: `has(resource.status.conditions)
&& resource.status.conditions.exists(c, c.type == "Ready" && c.status == "True")
&& resource.status.conditions.exists(c, c.type == "SlurmNodeStateDrain" && c.status == "True")
&& !resource.status.conditions.exists(c, c.type == "SlurmNodeStateUndrain" && c.status == "True")
&& !resource.status.conditions.exists(c, c.type == "SlurmNodeStateAllocated" && c.status == "True")
&& !resource.status.conditions.exists(c, c.type == "SlurmNodeStateMixed" && c.status == "True")
&& !resource.status.conditions.exists(c, c.type == "SlurmNodeStateCompleting" && c.status == "True")
&& (
  !has(lookup('v1', 'Node', '', resource.spec.nodeName).metadata.annotations)
  || !('nodeset.slinky.slurm.net/node-cordon-reason' in lookup('v1', 'Node', '', resource.spec.nodeName).metadata.annotations))`,
		nodeAssociation: `resource.spec.nodeName`,
	},
	{
		name:            "SlinkyOperatorDrainNoReboot",
		kind:            "Node",
		predicate:       `has(resource.metadata.annotations) && "nodeset.slinky.slurm.net/node-cordon-reason" in resource.metadata.annotations && !resource.metadata.annotations["nodeset.slinky.slurm.net/node-cordon-reason"].startsWith("[J] [NVSentinel]") && resource.spec.unschedulable && !resource.status.conditions.exists(c, c.type == "SlurmNodeRebootRequired" && c.status == "True")`,
		nodeAssociation: ``,
	},
	{
		name:            "SlinkyOperatorDrainWithReboot",
		kind:            "Node",
		predicate:       `has(resource.metadata.annotations) && "nodeset.slinky.slurm.net/node-cordon-reason" in resource.metadata.annotations && !resource.metadata.annotations["nodeset.slinky.slurm.net/node-cordon-reason"].startsWith("[J] [NVSentinel]") && has(resource.spec.unschedulable) && resource.spec.unschedulable && resource.status.conditions.exists(c, c.type == "SlurmNodeRebootRequired" && c.status == "True")`,
		nodeAssociation: ``,
	},
}

// TestRealPolicyFieldExtractionIsComplete asserts that every real policy yields
// a complete field set. An incomplete extraction is not itself a bug -- the
// caller is required to fall back to caching the object whole -- but it means
// the policy gets no memory saving, so it is worth knowing which ones do.
func TestRealPolicyFieldExtractionIsComplete(t *testing.T) {
	env, err := celenv.NewCompilerEnvironment()
	if err != nil {
		t.Fatalf("compiler environment: %v", err)
	}

	for _, p := range realPolicies {
		for _, expr := range []struct{ what, src string }{
			{"predicate", p.predicate},
			{"nodeAssociation", p.nodeAssociation},
		} {
			if expr.src == "" {
				continue
			}

			ast, err := env.Compile(expr.src)
			if err != nil {
				t.Errorf("%s/%s: compile: %v", p.name, expr.what, err)
				continue
			}

			paths, ok := celenv.ResourceFieldPaths(ast)
			if !ok {
				t.Logf("%s/%s: extraction incomplete, object must be cached whole", p.name, expr.what)
				continue
			}

			if len(paths) == 0 {
				t.Errorf("%s/%s: complete extraction returned no paths", p.name, expr.what)
			}

			t.Logf("%s/%s [%s]: %v", p.name, expr.what, p.kind, paths)
		}
	}
}

var _ = context.Background

// asPolicies converts the table into the config type derivePolicyFieldPaths takes.
func asPolicies() []config.Policy {
	out := make([]config.Policy, 0, len(realPolicies))

	for _, p := range realPolicies {
		pol := config.Policy{
			Name:      p.name,
			Enabled:   true,
			Resource:  config.ResourceSpec{Group: "", Version: "v1", Kind: p.kind},
			Predicate: config.PredicateSpec{Expression: p.predicate},
		}
		if p.nodeAssociation != "" {
			pol.NodeAssociation = &config.AssociationSpec{Expression: p.nodeAssociation}
		}

		out = append(out, pol)
	}

	return out
}

// TestRealPolicyCrossKindLookupFieldsSurvivePruning is the regression that
// matters. Three real policies are Pod policies that read fields off a Node
// through lookup(): GPUOperatorCudaValidatorMissingClique reads
// metadata.labels, SlinkySilentDrain reads metadata.annotations. Nothing in any
// Node policy reads metadata.labels, so if the lookup paths were not folded into
// the Node cache's transform, the Node would be cached without labels, the
// lookup would return an object missing them, and the predicate would evaluate
// false instead of true. That is a silent miss: no error, no log, just a GB200
// node with a missing clique that is never reported.
func TestRealPolicyCrossKindLookupFieldsSurvivePruning(t *testing.T) {
	compiler, err := celenv.NewCompilerEnvironment()
	if err != nil {
		t.Fatalf("compiler environment: %v", err)
	}

	derived := derivePolicyFieldPaths(compiler, asPolicies())

	nodeGVK := schema.GroupVersionKind{Group: "", Version: "v1", Kind: "Node"}

	node := derived.forGVK(nodeGVK)
	if node == nil {
		t.Fatal("no field paths derived for Node")
	}

	entry := node.cacheEntryFor(nodeGVK)
	if !entry.servesLookups {
		t.Fatal("Node cache does not serve lookups, so every lookup() falls back to a live API GET")
	}

	if entry.transform == nil {
		t.Skip("Node is cached whole, so nothing can be pruned away")
	}

	// Build a Node carrying exactly the fields the lookup policies read.
	obj := map[string]any{
		"apiVersion": "v1",
		"kind":       "Node",
		"metadata": map[string]any{
			"name": "node-1",
			"labels": map[string]any{
				"nvidia.com/gpu.product": "NVIDIA-GB200",
			},
			"annotations": map[string]any{
				"nodeset.slinky.slurm.net/node-cordon-reason": "drained by operator",
			},
		},
		"spec": map[string]any{"unschedulable": true},
		"status": map[string]any{
			"conditions": []any{
				map[string]any{"type": "Ready", "status": "True"},
			},
		},
	}

	u := &unstructured.Unstructured{Object: obj}

	out, err := entry.transform(u)
	if err != nil {
		t.Fatalf("transform: %v", err)
	}

	pruned, ok := out.(*unstructured.Unstructured)
	if !ok {
		t.Fatalf("transform returned %T", out)
	}

	meta, _ := pruned.Object["metadata"].(map[string]any)
	if meta == nil {
		t.Fatal("metadata pruned away entirely")
	}

	if _, ok := meta["labels"]; !ok {
		t.Error("metadata.labels pruned from the Node cache: " +
			"GPUOperatorCudaValidatorMissingClique reads it through lookup() and would silently never fire")
	}

	if _, ok := meta["annotations"]; !ok {
		t.Error("metadata.annotations pruned from the Node cache: " +
			"SlinkySilentDrain reads it through lookup() and would silently change behaviour")
	}

	if _, ok := meta["name"]; !ok {
		t.Error("metadata.name pruned: nodeAssociation reads it through lookup()")
	}

	t.Logf("Node object after pruning: %v", pruned.Object)
}

// richNode carries every field any real Node policy reads, with values chosen so
// the policies fire. Timestamps are old enough to clear the duration guards.
func richNode() map[string]any {
	old := "2020-01-01T00:00:00Z"

	return map[string]any{
		"apiVersion": "v1",
		"kind":       "Node",
		"metadata": map[string]any{
			"name":   "node-1",
			"labels": map[string]any{"nvidia.com/gpu.product": "NVIDIA-GB200"},
			"annotations": map[string]any{
				"nodeset.slinky.slurm.net/node-cordon-reason": "drained by operator",
			},
			"resourceVersion": "12345",
		},
		"spec": map[string]any{"unschedulable": true},
		"status": map[string]any{
			"conditions": []any{
				map[string]any{"type": "Ready", "status": "False", "lastTransitionTime": old, "lastHeartbeatTime": old},
				map[string]any{"type": "nke.nvidia.com/NeedsRepair", "status": "True", "lastTransitionTime": old},
				map[string]any{"type": "nke.nvidia.com/NeedsRecycle", "status": "True", "lastTransitionTime": old},
				map[string]any{"type": "us-east-1-aws.osmo.nvidia.com/SomethingBad", "status": "True", "lastTransitionTime": old},
				map[string]any{"type": "us-west-2-aws.osmo.nvidia.com/SomethingBad", "status": "True", "lastTransitionTime": old},
				map[string]any{"type": "SlurmNodeRebootRequired", "status": "True", "lastTransitionTime": old},
			},
			// Fields no policy reads. These must be pruned away, and their
			// absence must not change any result.
			"capacity":  map[string]any{"cpu": "64", "memory": "128Gi"},
			"images":    []any{map[string]any{"names": []any{"img-1"}, "sizeBytes": int64(1)}},
			"addresses": []any{map[string]any{"type": "InternalIP", "address": "10.0.0.1"}},
		},
	}
}

func richPod() map[string]any {
	return map[string]any{
		"apiVersion": "v1",
		"kind":       "Pod",
		"metadata": map[string]any{
			"name":                       "nvidia-operator-validator-abcde",
			"namespace":                  "osmo",
			"deletionTimestamp":          "2020-01-01T00:00:00Z",
			"deletionGracePeriodSeconds": int64(30),
			"annotations":                map[string]any{"unrelated": "x"},
		},
		"spec": map[string]any{"nodeName": "node-1"},
		"status": map[string]any{
			"phase": "Running",
			"conditions": []any{
				map[string]any{"type": "Ready", "status": "True"},
				map[string]any{"type": "SlurmNodeStateDrain", "status": "True"},
			},
			"initContainerStatuses": []any{
				map[string]any{"name": "cuda-validation", "restartCount": int64(5)},
			},
			"containerStatuses": []any{
				map[string]any{"name": "app", "state": map[string]any{"running": map[string]any{}}},
			},
			"podIP":     "10.1.2.3",
			"hostIP":    "10.0.0.1",
			"startTime": "2020-01-01T00:00:00Z",
		},
	}
}

// TestRealPolicyEvaluationUnchangedByPruning evaluates every real policy twice,
// once against the whole object and once against the object the cache would
// actually hold, and requires the two to agree. This is the check that the
// field analysis is not merely plausible but correct: if it drops a field a
// policy reads, the pruned evaluation diverges here.
//
// Policies using lookup() are evaluated for their non-lookup behaviour only;
// the lookup path is covered by TestRealPolicyCrossKindLookupFieldsSurvivePruning.
func TestRealPolicyEvaluationUnchangedByPruning(t *testing.T) {
	compiler, err := celenv.NewCompilerEnvironment()
	if err != nil {
		t.Fatalf("compiler environment: %v", err)
	}

	derived := derivePolicyFieldPaths(compiler, asPolicies())

	fixtures := map[string]func() map[string]any{"Node": richNode, "Pod": richPod}

	var fired int

	for _, p := range realPolicies {
		t.Run(p.name+"/"+p.kind, func(t *testing.T) {
			if containsLookup(p.predicate) {
				t.Skip("uses lookup(); covered by the cross-kind test")
			}

			gvk := schema.GroupVersionKind{Group: "", Version: "v1", Kind: p.kind}

			entry := derived.forGVK(gvk).cacheEntryFor(gvk)
			if entry.transform == nil {
				t.Skip("cached whole, nothing pruned")
			}

			ast, err := compiler.Compile(p.predicate)
			if err != nil {
				t.Fatalf("compile: %v", err)
			}

			full := fixtures[p.kind]()

			u := &unstructured.Unstructured{Object: fixtures[p.kind]()}

			out, err := entry.transform(u)
			if err != nil {
				t.Fatalf("transform: %v", err)
			}

			prunedObj, _ := out.(*unstructured.Unstructured)

			gotFull, err := compiler.Evaluate(ast, full, context.Background())
			if err != nil {
				t.Fatalf("evaluate full: %v", err)
			}

			gotPruned, err := compiler.Evaluate(ast, prunedObj.Object, context.Background())
			if err != nil {
				t.Fatalf("evaluate pruned: %v", err)
			}

			if gotFull.Value() != gotPruned.Value() {
				t.Errorf("pruning changed the result: full=%v pruned=%v\nretained object: %v",
					gotFull.Value(), gotPruned.Value(), prunedObj.Object)
			}

			if v, ok := gotFull.Value().(bool); ok && v {
				fired++
			}

			t.Logf("full=%v pruned=%v", gotFull.Value(), gotPruned.Value())
		})
	}

	if fired == 0 {
		t.Error("no policy evaluated true against its fixture, so agreement proves nothing")
	}
}

func containsLookup(s string) bool {
	for i := 0; i+7 <= len(s); i++ {
		if s[i:i+7] == "lookup(" {
			return true
		}
	}

	return false
}
