#!/usr/bin/env python3
"""Render a connector-pool StatefulSet that opens real MongoDB connections.

The existing connector-pool exercises only the Kubernetes connector
(enableMongoDBStorePlatformConnector=false), so it has never produced MongoDB
client load. This variant enables the MongoDB store connector and disables the
Kubernetes one, which isolates connection scaling from node-status write churn.

Each pod runs CONNECTORS_PER_POD independent platform-connector containers, each
with its own UDS and paired event-generator, so connector count is
CONNECTORS_PER_POD x replicas rather than being capped by pod count. A connector
uses about 10 MB in practice against its 512Mi limit, so density is bounded by
memory, not by pods.

Usage:
  gen-connector-pool-mongo.py --per-pod 10 --rate 0.1 > /tmp/pool.yaml
"""
import argparse

p = argparse.ArgumentParser()
p.add_argument("--per-pod", type=int, default=10)
p.add_argument("--replicas", type=int, default=0, help="start at 0; scale up deliberately")
p.add_argument("--rate", default="0.1", help="events/s per connector")
p.add_argument("--image", default="ghcr.io/nvidia/nvsentinel/platform-connectors:v1.20.0")
p.add_argument("--generator", default="docker.io/xrfxlp/event-generator:latest")
p.add_argument("--node-base", type=int, default=860000)
a = p.parse_args()

conn, gen = [], []
for i in range(a.per_pod):
    conn.append(f"""      - name: connector-{i}
        image: {a.image}
        args:
        - --socket=/var/run/connector/c{i}.sock
        - --config=/etc/config/config.json
        - --metrics-port={2112 + i}
        - --mongo-client-cert-mount-path=/etc/ssl/mongo-client
        envFrom:
        # Same source the real daemonset uses; supplies MONGODB_URI and the rest
        # of the datastore config. Without it the connector exits immediately.
        - configMapRef: {{name: nvsentinel-datastore-config, optional: true}}
        env:
        - name: MONGODB_CLIENT_CERT_MOUNT_PATH
          value: /etc/ssl/mongo-client
        - name: APP_NAME
          value: platform-connector
        - {{name: POD_NAME, valueFrom: {{fieldRef: {{fieldPath: metadata.name}}}}}}
        - name: NODE_NAME
          value: "pool-{i}"
        resources:
          requests: {{cpu: 10m, memory: 24Mi}}
          limits: {{cpu: 200m, memory: 128Mi}}
        volumeMounts:
        - {{name: socket-dir, mountPath: /var/run/connector}}
        - {{name: config, mountPath: /etc/config}}
        - {{name: mongo-cert, mountPath: /etc/ssl/mongo-client}}""")

    gen.append(f"""      - name: generator-{i}
        image: {a.generator}
        env:
        - {{name: EVENT_RATE, value: "{a.rate}"}}
        - {{name: POD_NAME, valueFrom: {{fieldRef: {{fieldPath: metadata.name}}}}}}
        command: [sh, -c]
        args:
        - |
          until [ -S /var/run/connector/c{i}.sock ]; do sleep 0.5; done
          ORD=${{POD_NAME##*-}}
          export NODE_NAME=$(printf "pb-%06d" $(( {a.node_base} + ORD * {a.per_pod} + {i} )))
          exec /root/event-generator --socket=/var/run/connector/c{i}.sock
        resources:
          requests: {{cpu: 5m, memory: 12Mi}}
          limits: {{cpu: 50m, memory: 32Mi}}
        volumeMounts:
        - {{name: socket-dir, mountPath: /var/run/connector}}""")

CONFIG_BODY = "\n".join("    " + ln for ln in open(__file__.rsplit("/",1)[0] + "/connector-pool-mongo-config.json").read().rstrip().splitlines())

OUT = f"""# Generated by gen-connector-pool-mongo.py --per-pod {a.per_pod} --rate {a.rate}
# Connectors = {a.per_pod} x replicas. Runs in the nvsentinel namespace to reuse
# the existing mongo-app-client-cert-secret and MongoDB service DNS.
#
# Scale deliberately and watch MongoDB connections between steps:
#   kubectl -n nvsentinel scale statefulset connector-pool-mongo --replicas=10
apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-pool-mongo-config
  namespace: nvsentinel
data:
  config.json: |
__CONFIG_JSON__
  metadata.toml: |
    cacheSize = 50
    cacheTTL = "3600s"
    allowedLabels = []
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connector-pool-mongo
  namespace: nvsentinel
spec:
  serviceName: connector-pool-mongo
  podManagementPolicy: Parallel
  replicas: {a.replicas}
  selector:
    matchLabels: {{app: connector-pool-mongo}}
  template:
    metadata:
      labels: {{app: connector-pool-mongo}}
    spec:
      tolerations:
      - {{key: dedicated, operator: Equal, value: system-workload, effect: NoSchedule}}
      - {{key: dedicated, operator: Equal, value: system-workload, effect: NoExecute}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {{key: "kwok.x-k8s.io/node", operator: DoesNotExist}}
      containers:
{chr(10).join(conn)}
{chr(10).join(gen)}
      volumes:
      - {{name: socket-dir, emptyDir: {{}}}}
      - {{name: config, configMap: {{name: connector-pool-mongo-config}}}}
      - name: mongo-cert
        secret:
          secretName: mongo-app-client-cert-secret
          items:
          - {{key: tls.crt, path: tls.crt}}
          - {{key: tls.key, path: tls.key}}
          - {{key: ca.crt, path: ca.crt}}"""

print(OUT.replace("__CONFIG_JSON__", CONFIG_BODY))
